# -*- mode: ruby -*-
# vi: set ft=ruby :

$instance_name = "centos7-java-dev"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/gentoo"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 80

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.

  # config.vm.network "private_network", ip: "192.168.33.11"
  # config.vm.network "private_network", type: "dhcp"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  # custom share folders...
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # this, plus your public rsa/dsa configuration gives you the ability to
  # ssh into the VM as an alternate user

  config.ssh.forward_agent = true

end
